### ISSUE TITLE
If you are engulfed and kill the engulfer by throwing a tethered aklys the game panics

### ISSUE THREAD

**Issue by amateurhourrrr** [Soviet5lo/SlashTHEM#48]
It can be easily reproduced in wizard mode by summoning a purple worm, and wishing for a +100 aklys

This might be a similar problem to one that was fixed in vanilla: https://github.com/NetHack/NetHack/commit/348f96813290594e794648e357b7eb89568a50e

**Comment by Soviet5lo** [comment]
Looks like a commit I missed while porting over tethering.  I'll see if I can get this fixed later this evening.

**Comment by Soviet5lo** [comment]
Looks like it's quite a few commits I'm missing that ended up modifying throwit in dothrow.c for vanilla.  Fix applied but I'm getting a different crash under the same circumstance.

```
tmp_at: tglyph not initialized
```

Probably another commit I'm missing somewhere.

**Comment by amateurhourrrr** [comment]
That sounds like it could include c6a5ec1a

**Comment by Soviet5lo** [comment]
This _should_ be fixed in db4ab9ce but to be honest I have no idea how it's fixed.  Haven't touched the code in a few days but its working fine now and no idea why; I fully expect some bugs to pop up from this.

Leaving this open for about another week in case this is an instance of "Works on my machine".
