### ISSUE TITLE
Killing a monster with bullets crashes the game

### ISSUE THREAD

**Issue by amateurhourrrr** [Soviet5lo/SlashTHEM#57]
If `thitmon` in src/dothrow.c:1259 returns truthy the object may have already been freed

The code then sets `thrownobj` to be null but `obj` is still a pointer to the (now-freed) memory
Immediately it reads from `obj` (read-after-free), and assuming the data still exists after being freed then immediately tries to free a second time which on many platforms including public servers crashes the game (double-free)

**Comment by Soviet5lo** [comment]
This was almost certainly introduced by [this commit](https://github.com/Soviet5lo/SlashTHEM/commit/db4ab9ce1519ac19583d6d4d6e9e52dd9d3fe940) to fix a crash related to aklys throwing.  This definitely needs to be fixed before June (assuming it takes part in Junethack this year).  Not too much free time at the moment however due to projects at work, but I'll see if I can get something done.

**Comment by transcendreamer** [comment]
I confirm that firing with bullets crashes the game (but sometimes not).

**Comment by Soviet5lo** [comment]
This should be fixed in commit 688cbb09
